### ISSUE TITLE
Nasadenie a .net 4.0

### ISSUE THREAD

**Issue by b-mi** [PavlinII/PayBySquare.TextGenerator.NET#1]
Zdravim,
je tato funkcnost nasadena aj v realnej prevadzke? 

Da sa pri prevode pri do .net 4.0 ocakavat nejaky problem?

Dakujem

**Comment by PavlinII** [comment]
Ahoj @b-mi,

Tu knihovnu s target .NET Standard 2.0 používáme v reálném provozu pod .NET Framework 4.0 na klientských PC a .NET Framework 4.8 na serverech. Není s tím žádný problém a je to kompatibilní i s .NET Core a .NET 5.

Ta implementace nepoužívá téměř žádné třídy z frameworku ani žádné závislosti. Takže pokud to celé zkopírujete do svého projektu, tak to bude fungovat bez problémů.

**Comment by b-mi** [comment]
Vdaka, medzicasom som na to prisiel. Funguje vyborne, skvela kniznica.
