### ISSUE TITLE
Problem with some banks

### ISSUE THREAD

**Issue by srnanek** [PavlinII/PayBySquare.TextGenerator.NET#3]
I found problem with some banks. I think the problem is with BIC code. Some banks checking BIC code in QR code and if you create QR code without BIC code the return from QR scener return "Bad QR Code".

SK: Testoval som to vo viacerých bankách. A pokiaľ som vytvoril QR kód bez BIC kódu tak mi appka banky vypísala že QR kód je chybný.

**Comment by PavlinII** [comment]
Zdravim,

V čem je podstata toho problému, případně jakou úpravu navrhujete? Třída `BankAccount` umožňuje k účtu zadat i IBAN.

**Comment by srnanek** [comment]
Problém bol že pokiaľ som použil IBAN a nevypísal BIC/SWIFT kód. Tak som dostal nevalidný QR kód. Musel som vyplniť aj IBAN aj BIC. 
On to nie je nejaký problém ale zdá sa že appky niektorých bánk si overuje informácie ktoré sa odosielajú a pokiaľ BIC/Swift nekorešponduje s  IBAN-om tak to validuje ako chybu.  Konkrétne mi tak fungovali ČSOB a MBank.
