### ISSUE TITLE
Standalone C# implementation

### ISSUE THREAD

**Issue by malyj1981** [PavlinII/PayBySquare.TextGenerator.NET#4]
Hello,
in attachment you can find standalone C# implementation which I got from ILSpy.

Just change the namespace and include in your project :-)

Regards and thank you for great work of implementing PayBySquare!

[PayBySquareHelper.zip](https://github.com/PavlinII/PayBySquare.TextGenerator.NET/files/11448685/PayBySquareHelper.zip)

**Comment by PavlinII** [comment]
I could have written it in C#, but I don't like it :)
